version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
    groups:
      eslint:
        patterns:
          - 'eslint*'
          - '@eslint/*'
          - 'typescript-eslint'
      electron:
        patterns:
          - 'electron'
          - 'electron-*'
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
