/// The two sanctioned ways to reach the pasteboard, and the vocabulary of the
/// second.
///
/// Until 2026-09-06 there was one: an explicit click of *Copy*, arriving as the
/// `copy` command. `contracts/helper-protocol.md` §5.1 records the repeal of the
/// rule that made it the only one, what replaced it, and what it cost. The rule
/// now is **the pasteboard is written, never read**, and
/// `ClipboardDisciplineTests` enforces it structurally and behaviourally.
///
/// Neither route is implemented here. `PasteboardWriting` is the seam the `copy`
/// command goes through, implemented by `SystemPasteboard` in the executable;
/// the paste tier's promise is `PromisedPasteboardOwner`, also in the
/// executable. What lives here is the part that is *data* rather than syscall —
/// which types a promise declares — so that a test can assert the list without a
/// windowserver and the executable cannot quietly drift from it.

public protocol PasteboardWriting: AnyObject {
    func write(_ text: String)
}

/// The types a promised pasteboard item declares, and nothing else.
public enum PasteboardPromise {
    /// The transcript itself. A request for **this** type, and only this one, is
    /// the read receipt the paste tier settles on.
    public static let textType = "public.utf8-plain-text"

    /// nspasteboard.org's convention for "do not record this in history".
    public static let transientType = "org.nspasteboard.TransientType"

    /// …and for "no human pressed ⌘C for it". The two are a convention, not an
    /// enforcement: Maccy honours them, others do not, and the maintainers of
    /// the convention publicly disagree about whether AutoGenerated implies
    /// transient. Some users' clipboard history will capture transcripts, and
    /// that is a limit of the approach rather than a bug in this list.
    public static let autoGeneratedType = "org.nspasteboard.AutoGeneratedType"

    /// Ours, carrying a per-publication UUID. Written, never read — see
    /// `PromisedPasteboardOwner.sessionType`.
    public static let sessionType = "com.fynnius.grokdictate.PasteSession"

    /// **`org.nspasteboard.ConcealedType` is deliberately absent.** It signals
    /// password-grade content, which is untrue of a dictation transcript and
    /// makes some clipboard managers visually obfuscate it. FluidVoice's
    /// reasoning, and it is right: claiming more protection than the content
    /// warrants makes the manager behave worse, not better.
    public static let declaredTypes = [
        textType, transientType, autoGeneratedType, sessionType,
    ]
}
