/// The syscalls behind the paste tier: a promised pasteboard item and a ⌘V
/// chord. The *decisions* — when a receipt counts, when to settle — are in
/// `HelperCore/PasteTransaction.swift`, which is pure and unit-tested.
///
/// **Nothing here ever reads the pasteboard.** Contract §5: the pasteboard is
/// written, never read. Reading is the operation macOS 15.4 previewed a prompt
/// for and macOS 26 carries; writing never prompts. A design that only writes is
/// immune to that permanently, which is why there is no snapshot and no restore
/// anywhere in this file.
///
/// The mechanism is Handy's (`src-tauri/src/paste_tx/`, MIT). Read, understood,
/// and reimplemented against this codebase — no source copied, and the split
/// between a pure decision and a thin syscall binding is ours rather than
/// theirs. The idea deserves the attribution: *do not put data on the
/// pasteboard, put a promise on it and let macOS tell you when someone reads
/// it.*

import AppKit
import CoreGraphics
import Foundation
import HelperCore

/// A pasteboard publication with no data behind it.
///
/// `declareTypes:owner:` announces which types are available; AppKit calls back
/// on `pasteboard:provideDataForType:` only when a consumer actually asks for
/// one. **That callback is a read receipt** — the only native signal on macOS
/// that says "the target took our text", and a strictly stronger one than
/// either verifier this repo used to ship, because it works in applications
/// whose AX text length is permanently zero.
///
/// **Lifetime.** AppKit holds the owner *weakly* (`declareTypes(_:owner:)` takes
/// `Any?` and does not retain it). If this object is deallocated before the
/// target reads, the promise resolves to nothing and the user pastes an empty
/// string. Whoever publishes must hold a strong reference until the transaction
/// settles — `PasteInserter` does, on the stack of the insertion it belongs to.
///
/// **Threading.** Both callbacks arrive on the run loop that was current when
/// `publish` was called, which for this process must be the main one (see the
/// note at the top of `HelperApp.swift`). They are handed straight to the
/// closures; the closures are responsible for being main-thread-safe.
final class PromisedPasteboardOwner: NSObject, NSPasteboardTypeOwner {
    /// Marker types honoured by the clipboard-manager convention at
    /// nspasteboard.org. Transient means "do not record this in history";
    /// AutoGenerated means "no human pressed ⌘C for it".
    ///
    /// `org.nspasteboard.ConcealedType` is deliberately **not** here. It signals
    /// password-grade content, which is untrue of a dictation transcript and
    /// makes some managers visually obfuscate it — FluidVoice's reasoning, and
    /// it is right.
    static let transientType = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
    static let autoGeneratedType = NSPasteboard.PasteboardType(
        "org.nspasteboard.AutoGeneratedType")
    /// Ours, carrying a per-publication UUID.
    ///
    /// **Written, never read** — by us or by anything else. It exists so that a
    /// clipboard manager, a `pbpaste -Prefer`, or a person reading a bug report
    /// can tell a Grok Dictate publication apart from a user's own ⌘C. Nothing
    /// in the settle path consults it: ownership is decided by `changeCount`
    /// and `pasteboardChangedOwner:`, both of which are answers from the OS,
    /// and a UUID we would have to *read back* to use would reintroduce exactly
    /// the pasteboard read this design exists to avoid.
    static let sessionType = NSPasteboard.PasteboardType("com.fynnius.grokdictate.PasteSession")

    static let declaredTypes: [NSPasteboard.PasteboardType] = [
        .string, transientType, autoGeneratedType, sessionType,
    ]

    /// What a `provideDataForType:` callback means, classified here so that
    /// nothing above this file has to know an `NSPasteboard.PasteboardType`.
    ///
    /// The distinction is the difference between a receipt and a rumour. A
    /// clipboard manager reacting to the pasteboard change asks for the marker
    /// types, because that is how it decides whether to record the entry; only
    /// a request for the *text* means someone is about to put our transcript
    /// somewhere.
    enum Request: Equatable {
        /// A consumer asked for the transcript. **This is the read receipt.**
        case text
        /// Something inspected one of our markers. Not a receipt.
        case marker(String)
    }

    /// The general pasteboard's current change count.
    ///
    /// The ownership token, and the only thing this design ever reads from the
    /// pasteboard — a counter, not content. It does not trip the privacy
    /// machinery in macOS 15.4+, which gates access to pasteboard *data*.
    static var currentChangeCount: Int { NSPasteboard.general.changeCount }

    private let text: String
    private let sessionId = UUID().uuidString
    private let onRequest: (Request) -> Void
    private let onOwnershipLost: () -> Void

    init(
        text: String,
        onRequest: @escaping (Request) -> Void,
        onOwnershipLost: @escaping () -> Void
    ) {
        self.text = text
        self.onRequest = onRequest
        self.onOwnershipLost = onOwnershipLost
    }

    /// Publish the promise. Returns the pasteboard's new `changeCount`, which is
    /// the token the settle path checks ownership against.
    @discardableResult
    func publish(to pasteboard: NSPasteboard = .general) -> Int {
        pasteboard.declareTypes(Self.declaredTypes, owner: self)
    }

    /// Settle: take the transcript back off the pasteboard.
    ///
    /// `clearContents()` and nothing else — no restore, because restoring would
    /// mean having read the previous contents. The user's earlier clipboard is
    /// gone; that trade is stated in `README.md` and in the settings copy.
    ///
    /// Returns `false` when somebody else has taken the pasteboard since
    /// `expectedChangeCount`, in which case nothing is touched: their copy wins.
    @discardableResult
    func clear(from pasteboard: NSPasteboard = .general, ifChangeCountIs expected: Int) -> Bool {
        guard pasteboard.changeCount == expected else { return false }
        pasteboard.clearContents()
        return true
    }

    // MARK: - NSPasteboardTypeOwner

    @objc func pasteboard(
        _ pasteboard: NSPasteboard,
        provideDataForType type: NSPasteboard.PasteboardType
    ) {
        switch type {
        case .string:
            pasteboard.setString(text, forType: type)
            onRequest(.text)
        case Self.sessionType:
            pasteboard.setString(sessionId, forType: type)
            onRequest(.marker(type.rawValue))
        default:
            // The two nspasteboard.org markers are flags, not payloads. An empty
            // string is what the convention expects and what every manager that
            // honours it reads.
            pasteboard.setString("", forType: type)
            onRequest(.marker(type.rawValue))
        }
    }

    @objc func pasteboardChangedOwner(_ pasteboard: NSPasteboard) {
        onOwnershipLost()
    }
}

/// The ⌘V chord.
enum PasteChord {
    /// The **physical** V key, `kVK_ANSI_V`.
    ///
    /// Hard-coded rather than derived from the current layout, and that is not
    /// laziness. Keyboard layouts whose name ends in `⌘` remap to QWERTY while
    /// Command is held, so resolving "the key that produces v" against the live
    /// layout yields the wrong keycode for exactly the users who need it right.
    /// VoiceInk hit this and ships `key code 9` for the same reason.
    static let virtualKeyV: CGKeyCode = 0x09

    enum Route: Equatable {
        /// Straight into one process's event queue, past every global tap.
        case pid(pid_t)
        /// The HID level, where Espanso, cliclick and Karabiner put their
        /// events. Reaches the widest set of applications.
        case hidTap
    }

    /// Post ⌘V. Returns false only if the events could not be constructed —
    /// `CGEvent.post` and `postToPid` have no return channel, which is the whole
    /// reason the receipt exists.
    ///
    /// Two details are load-bearing and are the same two `UnicodeInserter`
    /// documents at length:
    ///
    /// 1. `CGEventSource(stateID: .privateState)`. A source built from
    ///    `.hidSystemState` inherits the *physically held* modifiers, and the
    ///    retry hotkey is ⌃⌘V — a chord that picks up a stray Control is not
    ///    paste, it is the retry hotkey firing again.
    /// 2. Flags cleared and then set to exactly `.maskCommand`, on both the
    ///    key-down and the key-up. `= [.maskCommand]` rather than
    ///    `.insert(.maskCommand)` so there is no state to inherit.
    ///
    /// Callers must have waited on `ModifierSettle` first, for the half of the
    /// problem that lives in the *target's* reading of global hardware state.
    static func post(route: Route) -> Bool {
        guard
            let source = CGEventSource(stateID: .privateState),
            let keyDown = CGEvent(
                keyboardEventSource: source, virtualKey: virtualKeyV, keyDown: true),
            let keyUp = CGEvent(
                keyboardEventSource: source, virtualKey: virtualKeyV, keyDown: false)
        else { return false }

        keyDown.flags = [.maskCommand]
        keyUp.flags = [.maskCommand]

        switch route {
        case let .pid(pid):
            keyDown.postToPid(pid)
            keyUp.postToPid(pid)
        case .hidTap:
            keyDown.post(tap: .cghidEventTap)
            keyUp.post(tap: .cghidEventTap)
        }
        return true
    }
}
